import { createClient } from '@supabase/supabase-js'
import PptxGenJS from 'pptxgenjs'

function getSupabase() {
  return createClient(
    process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY
  )
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST')
    return res.status(405).json({ error: 'Method not allowed' })
  }

  try {
    const { reportId, userId } = req.body
    if (!reportId || !userId) {
      return res.status(400).json({ error: 'Missing required fields: reportId and userId' })
    }

    const supabase = getSupabase()

    const { data: report, error: reportError } = await supabase
      .from('reports')
      .select('id, user_id, title, kpis, executive_summary, extracted_data')
      .eq('id', reportId)
      .eq('user_id', userId)
      .single()

    if (reportError) {
      return res.status(403).json({ error: 'Report not found: ' + reportError.message })
    }
    if (!report) {
      return res.status(403).json({ error: 'Report not found or access denied' })
    }

    const extracted = report.extracted_data || {}
    const key_findings = extracted.key_findings || []
    const time_period = extracted.time_period || 'N/A'
    const kpis = report.kpis || []
    const execSummary = report.executive_summary || ''
    const today = new Date().toLocaleDateString('en-GB', {
      day: 'numeric', month: 'short', year: 'numeric',
    })

    const pptx = new PptxGenJS()
    pptx.defineLayout({ name: 'WIDE', width: 10, height: 5.625 })
    pptx.layout = 'WIDE'
    pptx.author = 'GetReportSync'

    // ── Colors ──
    const BLUE = '2563EB'
    const DARK = '0A0F1E'
    const WHITE = 'FFFFFF'
    const BODY = '1E293B'
    const MUTED = '64748B'
    const LIGHT_GRAY = 'F1F5F9'

    // ═══ Slide 1 — Title (dark background) ═══
    const slide1 = pptx.addSlide()
    slide1.background = { color: DARK }
    slide1.addText(report.title, {
      x: 0.5, y: 1.5, w: 9, h: 1.5,
      fontSize: 32, bold: true, color: WHITE, fontFace: 'Arial',
    })
    slide1.addText(time_period, {
      x: 0.5, y: 2.8, w: 9, h: 0.5,
      fontSize: 14, color: '94A3B8', fontFace: 'Arial',
    })
    slide1.addText(`Generated by GetReportSync · ${today}`, {
      x: 0.5, y: 4.5, w: 9, h: 0.4,
      fontSize: 11, color: '475569', fontFace: 'Arial',
    })
    slide1.addShape(pptx.ShapeType.roundRect, {
      x: 0.5, y: 4.2, w: 2.5, h: 0.35,
      fill: { color: BLUE },
    })
    slide1.addText('CONFIDENTIAL', {
      x: 0.6, y: 4.22, w: 2.3, h: 0.3,
      fontSize: 9, color: WHITE, fontFace: 'Arial', bold: true,
    })

    // ═══ Slide 2 — Key Metrics ═══
    const slide2 = pptx.addSlide()
    slide2.background = { color: WHITE }
    slide2.addText('Key Metrics', {
      x: 0.5, y: 0.3, w: 9, h: 0.7,
      fontSize: 20, bold: true, color: DARK, fontFace: 'Arial',
    })

    if (kpis.length > 0) {
      const cols = 3
      const gap = 0.3
      const cardW = (9 - (cols - 1) * gap) / cols
      const cardH = 1.2
      const startY = 1.3

      kpis.forEach((kpi, i) => {
        const col = i % cols
        const row = Math.floor(i / cols)
        const cx = 0.5 + col * (cardW + gap)
        const cy = startY + row * (cardH + gap)

        // Card
        slide2.addShape(pptx.ShapeType.roundRect, {
          x: cx, y: cy, w: cardW, h: cardH,
          fill: { color: LIGHT_GRAY },
          border: { color: 'E2E8F0', width: 1 },
        })

        // Value
        slide2.addText(`${kpi.value || ''}${kpi.unit || ''}`, {
          x: cx + 0.15, y: cy + 0.15, w: cardW - 0.3, h: 0.5,
          fontSize: 18, bold: true, color: DARK, fontFace: 'Arial',
        })
        // Label
        slide2.addText(kpi.label || '', {
          x: cx + 0.15, y: cy + 0.65, w: cardW - 0.3, h: 0.3,
          fontSize: 10, color: MUTED, fontFace: 'Arial',
        })
        // Change
        if (kpi.change_pct != null) {
          const up = kpi.trend === 'up'
          slide2.addText(`${up ? '↑' : '↓'} ${Math.abs(kpi.change_pct)}%`, {
            x: cx + 0.15, y: cy + 0.9, w: cardW - 0.3, h: 0.25,
            fontSize: 10, bold: true, color: up ? '16A34A' : 'DC2626', fontFace: 'Arial',
          })
        }
      })
    } else {
      slide2.addText('No metrics available for this report.', {
        x: 0.5, y: 2, w: 9, h: 0.5,
        fontSize: 13, color: MUTED, fontFace: 'Arial',
      })
    }

    // ═══ Slide 3 — Executive Summary ═══
    const slide3 = pptx.addSlide()
    slide3.background = { color: WHITE }
    slide3.addText('Executive Summary', {
      x: 0.5, y: 0.3, w: 9, h: 0.7,
      fontSize: 20, bold: true, color: DARK, fontFace: 'Arial',
    })
    // Blue left border bar
    slide3.addShape(pptx.ShapeType.rect, {
      x: 0.3, y: 1.2, w: 0.08, h: 3.8,
      fill: { color: BLUE },
    })
    // Text
    slide3.addText(execSummary || 'No executive summary available.', {
      x: 0.6, y: 1.2, w: 8.5, h: 3.8,
      fontSize: 13, color: BODY, fontFace: 'Arial',
      valign: 'top', lineSpacingMultiple: 1.5,
    })

    // ═══ Slide 4+ — Key Findings ═══
    if (key_findings.length > 0) {
      const chunkSize = 5
      for (let i = 0; i < key_findings.length; i += chunkSize) {
        const chunk = key_findings.slice(i, i + chunkSize)
        const slide4 = pptx.addSlide()
        slide4.background = { color: WHITE }
        slide4.addText('Key Findings', {
          x: 0.5, y: 0.3, w: 9, h: 0.7,
          fontSize: 20, bold: true, color: DARK, fontFace: 'Arial',
        })

        chunk.forEach((finding, j) => {
          const fy = 1.3 + j * 0.85

          // Accent dot
          slide4.addShape(pptx.ShapeType.ellipse, {
            x: 0.5, y: fy + 0.08, w: 0.15, h: 0.15,
            fill: { color: BLUE },
          })

          // Text
          slide4.addText(finding, {
            x: 0.8, y: fy, w: 8.5, h: 0.7,
            fontSize: 13, color: BODY, fontFace: 'Arial',
            valign: 'top',
          })
        })
      }
    }

    // ═══ Generate buffer ═══
    const pptxBuffer = await pptx.write({ outputType: 'nodebuffer' })

    // ═══ Upload to Supabase Storage ═══
    const filePath = `${userId}/pptx-${reportId}.pptx`
    const { error: uploadError } = await supabase.storage
      .from('exports')
      .upload(filePath, pptxBuffer, {
        contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        upsert: true,
      })

    if (uploadError) throw uploadError

    const { data: urlData, error: urlError } = await supabase.storage
      .from('exports')
      .createSignedUrl(filePath, 3600)

    if (urlError) throw urlError

    return res.status(200).json({ signedUrl: urlData.signedUrl })
  } catch (err) {
    console.error('[export-pptx] Handler error:', err)
    return res.status(500).json({
      error: 'Failed to generate PPTx export: ' + (err.message || 'Unknown error')
    })
  }
}
