import { createClient } from '@supabase/supabase-js'
import { Presentation } from 'pptxgenjs'

// Initialize Supabase client with service role key for backend operations
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SERVICE_ROLE_KEY
)

export default async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST')
    return res.status(405).end('Method Not Allowed')
  }

  try {
    const { reportId, userId } = req.body

    // Validate required fields
    if (!reportId || !userId) {
      return res.status(400).json({ 
        error: 'Missing required fields: reportId and userId'
      })
    }

    // Verify the report belongs to the user (security check)
    const { data: report, error: reportError } = await supabase
      .from('reports')
      .select('id, user_id, title, document_type, kpis, executive_summary, key_findings, time_period')
      .eq('id', reportId)
      .eq('user_id', userId)
      .single()

    if (reportError || !report) {
      return res.status(403).json({ 
        error: 'Unauthorized: Report not found or access denied'
      })
    }

    // Create a new presentation
    const pptx = new Presentation()

    // Set layout to be consistent
    pptx.layout = 'LAYOUT_TITLE'
    pptx.title = report.title

    // Define colors
    const blue = { color: '2563EB' } // Hex for #2563EB
    const darkGray = { color: '1F2937' }
    const gray = { color: '6B7280' }

    // Slide 1: Title Slide
    let slide = pptx.addSlide()
    slide.addText(report.title, {
      x: 0.5, y: 1.5, w: 9, h: 2,
      fontSize: 32, bold: true, color: '2563EB', align: 'center'
    })
    slide.addText(`Report type: ${report.document_type} | Period: ${report.time_period}`, {
      x: 0.5, y: 3.5, w: 9, h: 1,
      fontSize: 18, color: '6B7280', align: 'center'
    })
    slide.addText('Generated by GetReportSync', {
      x: 0.5, y: 6.5, w: 9, h: 0.5,
      fontSize: 14, italic: true, color: '9CA3AF', align: 'center'
    })

    // Slide 2: Executive Summary
    slide = pptx.addSlide()
    slide.addText('Executive Summary', {
      x: 0.5, y: 0.5, w: 9, h: 1,
      fontSize: 24, bold: true, color: '2563EB'
    })
    // Add a left border accent
    slide.addShape(pptx.shapes.RECTANGLE, {
      x: 0.3, y: 1.5, w: 0.2, h: 4,
      fill: { color: '2563EB' }
    })
    slide.addText(report.executive_summary || 'No executive summary available.', {
      x: 0.6, y: 1.5, w: 8.5, h: 4,
      fontSize: 16, color: '1F2937', lineSpacing: 1.2
    })

    // Slide 3: Key Metrics (2x3 grid)
    slide = pptx.addSlide()
    slide.addText('Key Metrics', {
      x: 0.5, y: 0.5, w: 9, h: 1,
      fontSize: 24, bold: true, color: '2563EB'
    })

    if (Array.isArray(report.kpis) && report.kpis.length > 0) {
      // Define grid positions
      const positions = [
        { x: 0.5, y: 1.5 },
        { x: 3.5, y: 1.5 },
        { x: 6.5, y: 1.5 },
        { x: 0.5, y: 3.5 },
        { x: 3.5, y: 3.5 },
        { x: 6.5, y: 3.5 }
      ]

      report.kpis.slice(0, 6).forEach((kpi, index) => {
        const pos = positions[index]
        if (!pos) return

        // KPI box
        slide.addShape(pptx.shapes.RECTANGLE, {
          x: pos.x, y: pos.y, w: 2.8, h: 1.5,
          line: { color: 'D1D5DB' },
          fill: { color: 'FFFFFF' }
        })

        // Value
        slide.addText(kpi.value || 'N/A', {
          x: pos.x, y: pos.y + 0.2, w: 2.8, h: 0.6,
          fontSize: 20, bold: true, color: '2563EB', align: 'center'
        })

        // Label
        slide.addText(kpi.label || 'Metric', {
          x: pos.x, y: pos.y + 0.8, w: 2.8, h: 0.3,
          fontSize: 12, color: '6B7280', align: 'center'
        })

        // Unit (if exists)
        if (kpi.unit) {
          slide.addText(kpi.unit, {
            x: pos.x, y: pos.y + 1.1, w: 2.8, h: 0.2,
            fontSize: 10, color: '9CA3AF', align: 'center'
          })
        }

        // Change percentage (if exists)
        if (kpi.change_pct !== undefined) {
          const changeText = `${kpi.change_pct > 0 ? '+' : ''}${kpi.change_pct}%`
          slide.addText(changeText, {
            x: pos.x, y: pos.y + 1.3, w: 2.8, h: 0.2,
            fontSize: 10, color: kpi.change_pct > 0 ? '10B981' : 'EF4444', align: 'center'
          })
        }
      })
    } else {
      slide.addText('No KPIs available.', {
        x: 0.5, y: 2, w: 9, h: 1,
        fontSize: 16, color: '6B7280', align: 'center'
      })
    }

    // Slides 4-N: Key Findings (max 5 per slide)
    if (Array.isArray(report.key_findings) && report.key_findings.length > 0) {
      const chunkSize = 5
      for (let i = 0; i < report.key_findings.length; i += chunkSize) {
        const chunk = report.key_findings.slice(i, i + chunkSize)
        slide = pptx.addSlide()
        slide.addText('Key Findings', {
          x: 0.5, y: 0.5, w: 9, h: 1,
          fontSize: 24, bold: true, color: '2563EB'
        })

        chunk.forEach((finding, index) => {
          const yPos = 1.5 + (index * 0.4)
          slide.addText(`• ${finding}`, {
            x: 0.8, y: yPos, w: 8.5, h: 0.3,
            fontSize: 14, color: '1F2937'
          })
        })
      }
    } else {
      slide = pptx.addSlide()
      slide.addText('Key Findings', {
        x: 0.5, y: 0.5, w: 9, h: 1,
        fontSize: 24, bold: true, color: '2563EB'
      })
      slide.addText('No key findings available.', {
        x: 0.5, y: 2, w: 9, h: 1,
        fontSize: 16, color: '6B7280', align: 'center'
      })
    }

    // Generate PPTX buffer
    const pptxBuffer = await pptx.writeBuffer({ fileType: 'pptx' })

    // Upload PPTX to Supabase Storage
    const filePath = `${userId}/report-${reportId}.pptx`
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('exports')
      .upload(filePath, pptxBuffer, {
        contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        upsert: true
      })

    if (uploadError) {
      throw uploadError
    }

    // Generate signed URL (valid for 1 hour)
    const { data: urlData, error: urlError } = await supabase.storage
      .from('exports')
      .createSignedUrl(filePath, 3600) // 3600 seconds = 1 hour

    if (urlError) {
      throw urlError
    }

    return res.status(200).json({ signedUrl: urlData.signedUrl })
  } catch (err) {
    console.error('[export-pptx] Handler error:', err)
    return res.status(500).json({ 
      error: 'Failed to generate PPTx export' 
    })
  }
}