import { createClient } from '@supabase/supabase-js'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

const supabase = createClient(
  process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

// Colours matching spec
const BLUE = rgb(37 / 255, 99 / 255, 235 / 255)      // #2563EB
const DARK_TEXT = rgb(0.059, 0.094, 0.165)            // #0F172A
const MUTED = rgb(0.392, 0.455, 0.545)                // #64748B
const LIGHT_BG = rgb(0.973, 0.98, 0.988)              // #F8FAFC
const BORDER = rgb(0.886, 0.909, 0.941)               // #E2E8F0
const WHITE = rgb(1, 1, 1)
const SUMMARY_BG = rgb(0.937, 0.965, 1)               // #EFF6FF
const GREEN = rgb(0.086, 0.635, 0.29)                 // #16A34A
const RED = rgb(0.863, 0.149, 0.149)                  // #DC2626

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST')
    return res.status(405).end('Method Not Allowed')
  }

  try {
    const { reportId, userId } = req.body
    if (!reportId || !userId) {
      return res.status(400).json({ error: 'Missing required fields: reportId and userId' })
    }

    const { data: report, error: reportError } = await supabase
      .from('reports')
      .select('id, user_id, title, kpis, executive_summary, extracted_data')
      .eq('id', reportId)
      .eq('user_id', userId)
      .single()

    if (reportError) {
      return res.status(403).json({ error: 'Report not found: ' + reportError.message })
    }
    if (!report) {
      return res.status(403).json({ error: 'Report not found or access denied' })
    }

    const extracted = report.extracted_data || {}
    const key_findings = extracted.key_findings || []
    const time_period = extracted.time_period || 'N/A'
    const kpis = report.kpis || []
    const execSummary = report.executive_summary || ''

    // Create PDF document
    const pdfDoc = await PDFDocument.create()
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
    const page = pdfDoc.addPage([595.28, 841.89]) // A4
    const pw = page.getWidth()
    const ph = page.getHeight()
    const margin = 50
    let y = ph - margin

    // ── Helper: wrapped text ──
    function wrapText(text, size, maxW, f = font) {
      const words = String(text).split(/\s+/)
      const lines = []
      let line = ''
      for (const w of words) {
        const test = line ? line + ' ' + w : w
        if (f.widthOfTextAtSize(test, size) > maxW) {
          if (line) { lines.push(line); line = w }
          else { lines.push(test); line = '' }
        } else {
          line = test
        }
      }
      if (line) lines.push(line)
      return lines
    }

    function drawText(text, size, color = DARK_TEXT, x = margin, yPos = y, f = font) {
      page.drawText(text, { x, y: yPos, size, font: f, color })
    }

    function drawWrapped(text, size, color = DARK_TEXT, x = margin, maxW = pw - 2 * margin, f = font) {
      const lines = wrapText(text, size, maxW, f)
      for (const line of lines) {
        if (y < margin + size) {
          // New page
          const p = pdfDoc.addPage([595.28, 841.89])
          y = ph - margin
        }
        drawText(line, size, color, x, y, f)
        y -= size * 1.4
      }
    }

    // ── Title ──
    drawText(report.title, 24, DARK_TEXT, margin, y, fontBold)
    y -= 32

    // ── Period line ──
    drawText(`Period: ${time_period} · Generated by GetReportSync · ${new Date().toLocaleDateString('en-GB')}`, 11, MUTED, margin, y)
    y -= 28

    // ── KPI Grid ──
    if (kpis.length > 0) {
      const cols = 3
      const gap = 12
      const cardW = (pw - 2 * margin - (cols - 1) * gap) / cols
      const cardH = 62

      kpis.forEach((kpi, i) => {
        const col = i % cols
        const row = Math.floor(i / cols)
        const cx = margin + col * (cardW + gap)
        const cy = y - row * (cardH + gap) - cardH

        // Card background
        page.drawRectangle({
          x: cx, y: cy, width: cardW, height: cardH,
          color: LIGHT_BG, borderColor: BORDER, borderWidth: 1,
        })

        // Value
        const val = `${kpi.value || ''}${kpi.unit || ''}`
        drawText(val, 18, DARK_TEXT, cx + 10, cy + cardH - 22, fontBold)
        // Label
        drawText(kpi.label || '', 10, MUTED, cx + 10, cy + 10)
        // Change
        if (kpi.change_pct != null) {
          const up = kpi.trend === 'up'
          const chg = `${up ? '↑' : '↓'} ${Math.abs(kpi.change_pct)}%`
          const cw = font.widthOfTextAtSize(chg, 10)
          drawText(chg, 10, up ? GREEN : RED, cx + cardW - cw - 10, cy + 10)
        }
      })

      const gridH = Math.ceil(kpis.length / cols) * (cardH + gap)
      y -= gridH + 16
    }

    // ── Executive Summary ──
    if (execSummary) {
      // Blue left border (rectangle)
      page.drawRectangle({
        x: margin, y: y - 10, width: 4, height: 60 + Math.min(execSummary.length, 400),
        color: BLUE,
      })
      // Label
      page.drawText('EXECUTIVE SUMMARY', {
        x: margin + 16, y: y + 4, size: 10, font: fontBold, color: BLUE,
      })
      y -= 18
      // Summary bg
      const summaryHeight = 24 + Math.min(execSummary.length * 0.3, 200)
      page.drawRectangle({
        x: margin, y: y - summaryHeight, width: pw - 2 * margin, height: summaryHeight,
        color: SUMMARY_BG,
      })
      // Text
      const savedY = y
      drawWrapped(execSummary.replace(/\n/g, ' '), 12, DARK_TEXT, margin + 16, pw - 2 * margin - 32)
      y = Math.min(y, savedY - summaryHeight + 10)
      y -= 20
    }

    // ── Key Findings ──
    if (key_findings.length > 0) {
      drawText('Key Findings', 14, DARK_TEXT, margin, y, fontBold)
      y -= 20

      for (const finding of key_findings) {
        if (y < margin + 24) {
          const p = pdfDoc.addPage([595.28, 841.89])
          y = ph - margin
        }

        // Arrow bullet
        page.drawText('→', { x: margin, y: y + 2, size: 12, font, color: BLUE })
        // Finding text
        const findingW = pw - margin * 2 - 20
        const flines = wrapText(finding, 12, findingW)
        for (const fl of flines) {
          drawText(fl, 12, DARK_TEXT, margin + 16, y)
          y -= 16
        }
        y -= 4
      }
      y -= 10
    }

    // ── Footer ──
    y = margin + 20
    const footerY = y
    page.drawLine({
      start: { x: margin, y: footerY + 10 },
      end: { x: pw - margin, y: footerY + 10 },
      color: BORDER, thickness: 1,
    })
    const today = new Date().toLocaleDateString('en-GB')
    drawText('GetReportSync.com', 10, MUTED, margin, footerY - 4)
    const mid = `${report.title} · Confidential`
    const midW = font.widthOfTextAtSize(mid, 10)
    drawText(mid, 10, MUTED, (pw - midW) / 2, footerY - 4)
    const dateW = font.widthOfTextAtSize(today, 10)
    drawText(today, 10, MUTED, pw - margin - dateW, footerY - 4)

    // ── Serialize ──
    const pdfBuffer = Buffer.from(await pdfDoc.save())

    // ── Upload to Supabase Storage ──
    const filePath = `${userId}/pdf-${reportId}.pdf`
    const { error: uploadError } = await supabase.storage
      .from('exports')
      .upload(filePath, pdfBuffer, {
        contentType: 'application/pdf',
        upsert: true,
      })

    if (uploadError) throw uploadError

    const { data: urlData, error: urlError } = await supabase.storage
      .from('exports')
      .createSignedUrl(filePath, 3600)

    if (urlError) throw urlError

    return res.status(200).json({ signedUrl: urlData.signedUrl })
  } catch (err) {
    console.error('[export-pdf] Handler error:', err)
    return res.status(500).json({
      error: 'Failed to generate PDF export: ' + (err.message || 'Unknown error')
    })
  }
}
