import { createClient } from '@supabase/supabase-js'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

// Initialize Supabase client with service role key for backend operations
const supabase = createClient(
  process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

// Colours
const BLUE = rgb(37 / 255, 99 / 255, 235 / 255)   // #2563EB
const DARK = rgb(0.11, 0.11, 0.11)                   // #1C1C1C
const GRAY = rgb(0.42, 0.42, 0.42)                   // #6B7280
const LIGHT_GRAY = rgb(0.9, 0.9, 0.9)                // #E5E7EB
const WHITE = rgb(1, 1, 1)

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST')
    return res.status(405).end('Method Not Allowed')
  }

  try {
    const { reportId, userId } = req.body

    if (!reportId || !userId) {
      return res.status(400).json({ error: 'Missing required fields: reportId and userId' })
    }

    // Fetch report data
    const { data: report, error: reportError } = await supabase
      .from('reports')
      .select('id, user_id, title, kpis, executive_summary, extracted_data')
      .eq('id', reportId)
      .eq('user_id', userId)
      .single()

    if (reportError) {
      return res.status(403).json({ error: 'Report not found: ' + reportError.message })
    }
    if (!report) {
      return res.status(403).json({ error: 'Report not found or access denied' })
    }

    const extracted = report.extracted_data || {}
    const key_findings = extracted.key_findings || []
    const time_period = extracted.time_period || ''
    const document_type = extracted.document_type || ''
    const kpis = Array.isArray(report.kpis) ? report.kpis : []
    const execSummary = report.executive_summary || ''

    // ── Create PDF ──
    const pdfDoc = await PDFDocument.create()
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
    
    const pageWidth = 595.28  // A4 width in points
    const pageHeight = 841.89 // A4 height in points
    const margin = 56         // ~2cm margin

    let page = pdfDoc.addPage([pageWidth, pageHeight])
    let y = pageHeight - margin

    // --- Helper to add text and track position ---
    function addLine(text, size = 11, color = DARK, bold = false, x = margin, indent = 0) {
      const f = bold ? fontBold : font
      const w = page.getWidth() - 2 * margin - indent
      const words = text.split(' ')
      let line = ''
      for (const word of words) {
        const test = line ? line + ' ' + word : word
        if (f.widthOfTextAtSize(test, size) > w) {
          page.drawText(line, { x: x + indent, y, size, font: f, color })
          y -= size * 1.45
          line = word
        } else {
          line = test
        }
      }
      if (line) {
        page.drawText(line, { x: x + indent, y, size, font: f, color })
        y -= size * 1.45
      }
    }

    function addDivider(yPos) {
      page.drawLine({
        start: { x: margin, y: yPos },
        end: { x: pageWidth - margin, y: yPos },
        thickness: 1.5,
        color: BLUE,
      })
    }

    // ══════ PAGE 1: HEADER ══════
    // Blue accent bar at top
    page.drawRectangle({
      x: 0, y: pageHeight - 6,
      width: pageWidth, height: 6,
      color: BLUE,
    })

    y -= 30
    // Title
    const titleSize = report.title.length > 40 ? 18 : 22
    page.drawText(report.title || 'Report', {
      x: margin, y, size: titleSize, font: fontBold, color: DARK,
    })
    y -= titleSize * 1.5

    // Meta
    const metaText = [document_type, time_period].filter(Boolean).join(' · ')
    if (metaText) {
      page.drawText(metaText, {
        x: margin, y, size: 10, font, color: GRAY,
      })
      y -= 20
    }

    // Generated date
    const dateStr = new Date().toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric'
    })
    page.drawText(`Generated by GetReportSync · ${dateStr}`, {
      x: margin, y, size: 9, font, color: GRAY,
    })
    y -= 30

    addDivider(y)
    y -= 25

    // ══════ EXECUTIVE SUMMARY ══════
    page.drawText('Executive Summary', {
      x: margin, y, size: 14, font: fontBold, color: BLUE,
    })
    y -= 22

    if (execSummary) {
      addLine(execSummary, 10.5, DARK)
    } else {
      addLine('No executive summary available.', 10.5, GRAY)
    }
    y -= 10

    // ══════ KEY METRICS ══════
    // Check if we need a new page
    if (y < 200) {
      page = pdfDoc.addPage([pageWidth, pageHeight])
      y = pageHeight - margin
    }

    page.drawText('Key Metrics', {
      x: margin, y, size: 14, font: fontBold, color: BLUE,
    })
    y -= 22

    if (kpis.length > 0) {
      // Draw KPI cards in a 2-column grid
      const cardW = (pageWidth - 3 * margin) / 2
      const cardH = 70
      const cols = 2

      for (let i = 0; i < kpis.length; i++) {
        const col = i % cols
        const row = Math.floor(i / cols)
        const cx = margin + col * (cardW + margin)
        const cy = y - row * (cardH + 15)

        // Need space — add page
        if (cy - cardH < margin + 40) {
          page = pdfDoc.addPage([pageWidth, pageHeight])
          y = pageHeight - margin - 40
          continue
        }

        // Card background
        page.drawRectangle({
          x: cx, y: cy - cardH,
          width: cardW, height: cardH,
          color: LIGHT_GRAY,
          borderColor: rgb(0.93, 0.93, 0.93),
          borderWidth: 1,
        })

        // KPI value
        const val = kpis[i].value || 'N/A'
        const valSize = val.length > 8 ? 18 : 24
        page.drawText(val, {
          x: cx + 12, y: cy - 24,
          size: valSize, font: fontBold, color: BLUE,
        })

        // KPI label
        page.drawText(kpis[i].label || 'Metric', {
          x: cx + 12, y: cy - 50,
          size: 10, font, color: GRAY,
        })

        // Change percentage
        if (kpis[i].change_pct != null) {
          const pct = kpis[i].change_pct
          const pctStr = `${pct > 0 ? '+' : ''}${pct}%`
          const pctColor = pct >= 0 ? rgb(0.06, 0.67, 0.18) : rgb(0.93, 0.27, 0.27)
          page.drawText(pctStr, {
            x: cx + cardW - 50, y: cy - 24,
            size: 10, font: fontBold, color: pctColor,
          })
        }
      }

      y = y - Math.ceil(kpis.length / cols) * (cardH + 15) - 15
    } else {
      addLine('No KPIs available.', 10.5, GRAY)
    }

    y -= 10

    // ══════ KEY FINDINGS ══════
    if (key_findings.length > 0) {
      if (y < 120) {
        page = pdfDoc.addPage([pageWidth, pageHeight])
        y = pageHeight - margin
      }

      addDivider(y)
      y -= 25

      page.drawText('Key Findings', {
        x: margin, y, size: 14, font: fontBold, color: BLUE,
      })
      y -= 22

      for (const finding of key_findings) {
        if (y < 40) {
          page = pdfDoc.addPage([pageWidth, pageHeight])
          y = pageHeight - margin
        }

        // Bullet dot
        page.drawCircle({
          x: margin + 4, y: y - 5,
          size: 3,
          color: BLUE,
        })

        // Finding text
        const maxW = pageWidth - 2 * margin - 20
        const findingSize = 10
        const words = finding.split(' ')
        let line = ''
        for (const word of words) {
          const test = line ? line + ' ' + word : word
          if (font.widthOfTextAtSize(test, findingSize) > maxW) {
            page.drawText(line, {
              x: margin + 16, y, size: findingSize, font, color: DARK,
            })
            y -= findingSize * 1.5
            line = word
          } else {
            line = test
          }
        }
        if (line) {
          page.drawText(line, {
            x: margin + 16, y, size: findingSize, font, color: DARK,
          })
          y -= findingSize * 1.5
        }
        y -= 6
      }
    }

    // ── Footer on every page ──
    const pages = pdfDoc.getPages()
    for (const p of pages) {
      const pw = p.getWidth()
      p.drawLine({
        start: { x: margin, y: 40 },
        end: { x: pw - margin, y: 40 },
        thickness: 0.5,
        color: GRAY,
      })
      p.drawText('GetReportSync · Confidential', {
        x: margin, y: 25,
        size: 8, font, color: GRAY,
      })
      p.drawText(`Page ${pages.indexOf(p) + 1} of ${pages.length}`, {
        x: pw - margin - 80, y: 25,
        size: 8, font, color: GRAY,
      })
    }

    // ── Serialize PDF ──
    const pdfBytes = await pdfDoc.save()

    // Upload to Supabase Storage
    const filePath = `${userId}/report-${reportId}.pdf`
    const { error: uploadError } = await supabase.storage
      .from('exports')
      .upload(filePath, pdfBytes, {
        contentType: 'application/pdf',
        upsert: true
      })

    if (uploadError) {
      console.error('[export-pdf] Upload error:', uploadError)
      throw uploadError
    }

    // Generate signed URL (valid for 1 hour)
    const { data: urlData, error: urlError } = await supabase.storage
      .from('exports')
      .createSignedUrl(filePath, 3600)

    if (urlError) throw urlError

    return res.status(200).json({ signedUrl: urlData.signedUrl })
  } catch (err) {
    console.error('[export-pdf] Handler error:', err)
    return res.status(500).json({ 
      error: 'Failed to generate PDF export: ' + (err.message || 'Unknown error')
    })
  }
}